#!/bin/sh

set -e

if [ "$1" = "configure" ] ; then
	update-alternatives --install /usr/bin/oslopolicy-sample-generator oslopolicy-sample-generator /usr/bin/python2-oslopolicy-sample-generator 300
	update-alternatives --install /usr/bin/oslopolicy-checker oslopolicy-checker /usr/bin/python2-oslopolicy-checker 300
	update-alternatives --install /usr/bin/oslopolicy-policy-generator oslopolicy-policy-generator /usr/bin/python2-oslopolicy-policy-generator 300
	update-alternatives --install /usr/bin/oslopolicy-list-redundant oslopolicy-list-redundant /usr/bin/python2-oslopolicy-list-redundant 300
fi

#DEBHELPER#

exit 0
