#!/bin/sh

set -e

if [ "$1" = "remove" ] ; then
	update-alternatives --remove oslopolicy-sample-generator /usr/bin/python3-oslopolicy-sample-generator
	update-alternatives --remove oslopolicy-checker /usr/bin/python3-oslopolicy-checker
	update-alternatives --remove oslopolicy-policy-generator /usr/bin/python3-oslopolicy-policy-generator
	update-alternatives --remove oslopolicy-list-redundant /usr/bin/python3-oslopolicy-list-redundant
fi

#DEBHELPER#

exit 0
