#!/bin/sh

set -e

if [ "$1" = "configure" ] ; then
	update-alternatives --install /usr/bin/oslopolicy-sample-generator oslopolicy-sample-generator /usr/bin/python3-oslopolicy-sample-generator 200
	update-alternatives --install /usr/bin/oslopolicy-checker oslopolicy-checker /usr/bin/python3-oslopolicy-checker 200
	update-alternatives --install /usr/bin/oslopolicy-policy-generator oslopolicy-policy-generator /usr/bin/python3-oslopolicy-policy-generator 200
	update-alternatives --install /usr/bin/oslopolicy-list-redundant oslopolicy-list-redundant /usr/bin/python3-oslopolicy-list-redundant 200
fi

#DEBHELPER#

exit 0
